image: gitpod/workspace-go:1.24.4

ports:
- port: 8080
checkoutLocation: lama
workspaceLocation: lama
tasks:
- command: |
    cd .. &&
    curl -OL https://github.com/goreleaser/goreleaser/releases/download/v0.108.0/goreleaser_Linux_x86_64.tar.gz &&
    tar xfz goreleaser_Linux_x86_64.tar.gz &&
    rm goreleaser_Linux_x86_64.tar.gz &&
    curl -OL https://github.com/upx/upx/releases/download/v3.95/upx-3.95-amd64_linux.tar.xz &&
    tar xf upx-3.95-amd64_linux.tar.xz &&
    mv upx-3.95-amd64_linux/upx . &&
    rm -rf upx-3.95-amd64_linux* &&
    cd lama
